########################### VARIÁVEIS GLOBAIS ####################
spring.main.allow-bean-definition-overriding=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url = jdbc:mysql://localhost:3306/gingabpm_prototipo_esign?useTimezone=true&serverTimezone=UTC&useSSL=false
#spring.datasource.url = jdbc:mysql://localhost:3306/db_solente_esign_teste?useTimezone=true&serverTimezone=UTC&useSSL=false



spring.jpa.show-sql=true
spring.session.jdbc.initialize-schema: always
spring.jpa.database-platform = org.hibernate.dialect.MySQL5Dialect
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto = update
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
server.port=9090
server.error.whitelabel.enabled=true
server.error.path=/error
config.token_key =715bc473-3b8c-4421-8a93-167b2efae24d
config.token_expiration =600000
#config.token_expiration =300000
config.header =Authorization
config.prefixo =Bearer
configs.esign.userginga=okmAdmin 
configs.esign.passginga=Prod!@2023!?
configs.esign.bpmusername=hossana.mosse
configs.esign.bpmpassword=@analista
configs.esign.password=$05$dvQAXdOgI1cO0lDY6h9I3.iJGreEGL94qizgnGpR7BmfRZkKtSN/m
configs.esign.apibaseurl=https://api.eu1.adobesign.com/api/rest/v6
configs.esign.refreshtokenurl=https://secure.eu1.adobesign.com/oauth/v2/refresh
########################### VARIÁVEIS GLOBAIS ####################

########################### CONFIGURACOES NA MAQUINA LOCAL ####################
#spring.datasource.username = root
#spring.datasource.password = root
#configs.esign.uploads=uploads/
#configs.esign.server= http://localhost:9090/api/v1
#configs.esign.url=    http://localhost:9090/api/v1/receiver
#configs.esign.ginga=  http://localhost:8082/api/v1/signature/response



##########################  FIM  DAS CONFIGURACOES LOCAIS ########################


######################### CONFIGFURACOES NO SERVIDOR #################################
spring.datasource.username = root
spring.datasource.password = root
configs.esign.uploads=/opt/prototipo_uploads/
configs.esign.server=http://92.204.138.167:8181/esign_prototipo_gingabpm/api/v1
configs.esign.url= http://92.204.138.167:8181/esign_prototipo_gingabpm/api/v1/receiver
configs.esign.ginga=http://92.204.138.167:8181/api_solente_testeI/api/v1/signature/response

############################  FIM  DAS CONFIGURACOES DO SERVIDOR ###########################


